# .github/workflows/updateProvider.yml
name: Update Provider

on:
    workflow_dispatch:
        inputs:
            providerId:
                description: "Provider ID"
                required: true
            updatedValues:
                description: "Updated Values"
                required: true

jobs:
    updateData:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Update data
              run: node scripts/updateProvider.js ${{ github.event.inputs.providerId }} '${{ toJSON(github.event.inputs.updatedValues) }}'

            - name: Create branch
              run: |
                  git checkout -b update-data-test

            - name: Commit and push changes
              run: |
                  git config --global user.name 'Bot'
                  git config --global user.email 'bot@example.com'
                  git add -A
                  git commit -m "Update data"
                  git push origin HEAD:update-data-test
              env:
                  GH_TOKEN: ${{ secrets.PAT_SECRET }}

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                  title: Update data
                  branch: update-data-test
                  github_token: ${{ secrets.PAT_SECRET }}
