# .github/workflows/updateData.yml
name: Update Provider

on:
    workflow_dispatch:
        inputs:
            providerId:
                description: "Provider ID"
                required: true
            updatedValues:
                description: "Updated Values"
                required: true

jobs:
    updateData:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install dependencies
              run: npm ci

            - name: Update data
              run: node scripts/updateProvider.js ${{ github.event.inputs.id }} ${{ github.event.inputs.updatedValues }}

            - name: Commit and push changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Update data
                  branch: create-pull-request

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                  title: Update data
                  branch: create-pull-request
