# .github/workflows/updateProvider.yml
name: Update Provider

on:
    workflow_dispatch:
        inputs:
            providerId:
                description: "Provider ID"
                required: true
            updatedValues:
                description: "Updated Values"
                required: true
            providerName:
                description: "Provider Name"
                required: true

jobs:
    updateData:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Update data
              run: node scripts/updateProvider.js ${{ github.event.inputs.providerId }} '${{ github.event.inputs.updatedValues }}'

            - name: Create branch
              run: |
                  git checkout -b update-${{ github.run_number }}

            - name: Commit and push changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Update data
                  branch: update-${{ github.run_number }}

            - name: Create Pull Request
              uses: repo-sync/pull-request@v2
              with:
                  source_branch: update-${{ github.run_number }}
                  destination_branch: main
                  pr_title: "Update ${{ github.event.inputs.providerName }} - Update number ${{ github.run_number }}"
                  pr_body: "${{ github.event.inputs.updatedValues }}"
                  pr_label: "automated-pr"
                  pr_reviewer: "EridianAlpha"
