# .github/workflows/updateProvider.yml
name: Update Provider

on:
    workflow_dispatch:
        inputs:
            providerId:
                description: "Provider ID"
                required: true
            updatedValues:
                description: "Updated Values"
                required: true

jobs:
    updateData:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                  title: Update data
                  branch: update-${{ github.run_number }}
                  commit-message: Update data
                  script: |
                      node scripts/updateProvider.js ${{ github.event.inputs.providerId }} '${{ toJSON(github.event.inputs.updatedValues) }}'
